apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: form-app-namespace  
  name: my-role-binding
subjects:
- kind: ServiceAccount
  name: my-service-account
  apiGroup: ""
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
