apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: form-app-namespace  
  name: my-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "create", "update", "delete"]
